services:
  server:
    image: royalflush-server:v1
    container_name: royalflush-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    environment: # LOCAL DEV
      GOOGLE_APPLICATION_CREDENTIALS: /app/royal-flush-storage-key.json
    volumes: # LOCAL DEV
      - ./royal-flush-storage-key.json:/app/royal-flush-storage-key.json:ro

    ports:
      - "3001:3001"
    restart: unless-stopped